### ISSUE TITLE
Upgrade to Quarkus 3

### ISSUE THREAD

**Issue by luca-bassoricci** [quarkiverse/quarkus-jberet#172]
Is there any plan to upgrade extension to Quarkus 3?

**Comment by radcortez** [comment]
Yes. I'll see if I can start the work in the next few weeks.

**Comment by radcortez** [comment]
Here is a branch with the Jakarta work: https://github.com/quarkiverse/quarkus-jberet/tree/jakarta

Everything seems to be working except the TCK, which requires some adjustments.

**Comment by amoscatelli** [comment]
@radcortez do you think could be interesting to integrate the Jpa based Job Repository ?

https://github.com/jberet/jberet-jpa-repository

Based on JPA it supports more dbs, caches and solves some issue related to JobExecutions removal.

I am asking here because it requires JBeret 2.0 (and so jakarta EE packages).

If you are interested I could try to integrate it myself (since I would use it for my projects) and make a pull request on the jakarta branch.

**Comment by radcortez** [comment]
Sure, feel free to propose something. I guess it should be a separate extension (like the `rest` one).

**Comment by amoscatelli** [comment]
Maybe I could extend the factory and register the extended one as default ...

**Comment by radcortez** [comment]
How about a CDI producer and look up the bean the same way we do with the `TransactionManager`?

**Comment by amoscatelli** [comment]
That's exactly what I thought too

**Comment by radcortez** [comment]
Or just add the JobRepository as a parameter, so you can lookup the bean in the Recorder method.
